[target.x86_64-apple-darwin.mirrorx_core]
# rustflags = [
#     "-C",
#     "link-args=-sectcreate __CGPreLoginApp __cgpreloginapp /dev/null",
# ]
rustc-link-search = ["../mirrorx_native/build/lib"]
rustc-link-lib = ["mirrorx_native"]
rustc-env = { mmacosx-version-min = "10.15" }

[target.x86_64-pc-windows-msvc]
