[package]
name = "mirrorx_core"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
log = "0.4.14"
env_logger = { version = "0.9.0", features = ["humantime"] }
chrono = "0.4.19"
rand = "0.8.5"
lazy_static = "1.4.0"
machine-uid = "0.2.0"
mac_address = "1.1.3"
reqwest = { version = "0.11.9", features = ["json", "blocking"] }
sha2 = "0.10.2"
hex = "0.4.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
flutter_rust_bridge = "1.22.2"
anyhow = "1.0.56"
rusqlite = { version = "0.27.0", features = ["bundled"] }

[build-dependencies]
cc = "1.0.73"