# pre-build process
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test","--tests"]

# build process
[tasks.build_debug]
mac_alias = "build_macos_debug"

[tasks.build_release]
mac_alias = "build_macos_release"
dependencies = ["clean"]

## debug build
[tasks.build_macos_debug]
command = "cargo"
args = ["build", "--target", "x86_64-apple-darwin"]

## release build
[tasks.build_macos_release]
command = "cargo"
args = ["build", "--target", "x86_64-apple-darwin", "--release"]

[tasks.make-debug]
dependencies = [
    "format",
    "test",
    "build_debug"
]

[tasks.make-release]
dependencies = [
    "format",
    "test",
    "build_release"
]