[package]
name = "mirrorx_core"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
chrono = "0.4.19"
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_bytes = "0.11.6"
flutter_rust_bridge = "1.34.2"
anyhow = "1.0.58"
rusqlite = { version = "0.27.0", features = ["bundled"] }
bytes = "1.1.0"
futures = "0.3.21"
tokio = { version = "1.19.2", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["full"] }
bincode = "1.3.3"
once_cell = "1.12.0"
dashmap = "5.3.4"
crossbeam = "0.8.1"
libc = "0.2.126"
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
scopeguard = "1.1.0"
arc-swap = "1.5.0"
hmac = "0.12.1"
sha2 = "0.10.2"
rsa = "0.6.1"
ring = "0.16.20"
pbkdf2 = "0.11"
thiserror = "1.0.31"
hex = "0.4.3"
cpal = "0.13.5"

[target.x86_64-apple-darwin.dependencies]
objc = { version = "0.2.7" }
objc-encode = "1.1.0"
block = "0.1.6"
dispatch = "0.2.0"
objc-foundation = "0.1.1"
objc_id = "0.1.1"
core-foundation = "0.9.3"
core-graphics = "0.22.3"

[target.x86_64-pc-windows-msvc.dependencies]
image = "0.24.2"
windows = { version = "0.38.0", features = [
  "alloc",
  "Win32_Foundation",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Gdi",
  "Win32_System_StationsAndDesktops",
  "Win32_System_SystemServices",
  "Win32_System_WindowsProgramming",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
  "Win32_Devices_Display",
] }

[profile.dev]
opt-level = 3

[profile.release]
lto = true
incremental = true
strip = true
