[package]
name = "mirrorx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mirrorx_core = { path = "../mirrorx_core" }
eframe = { version = "0.19.0", features = ["wgpu"] }
egui_extras = "0.19.0"
once_cell = "1.15.0"
directories-next = "2.0.0"
poll-promise = { version = "0.1.0", features = ["tokio"] }
tokio = "1.21.2"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
anyhow = "1.0.65"
# [patch.crates-io]

# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

# If you want to use the bleeding edge version of egui and eframe:
# egui = { git = "https://github.com/emilk/egui", branch = "master" }
# If you fork https://github.com/emilk/egui you can test with:
# egui = { path = "../egui/crates/egui" }
# eframe = { path = "../egui/crates/eframe" }
