name: build_macos

on:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: macos-latest
    steps:
    - name: setup nasm
      uses: ilammy/setup-nasm@v1.4.0
    - name: setup autoconf
      run: brew install autoconf
    - name: setup automake
      run: brew install automake
    - name: setup libtool
      run: brew install libtool
    - name: setup node.js
      uses: actions/setup-node@v3.5.1
    - name: setup protobuf
      run: brew install protobuf
    - name: setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: setup tauri-cli
      uses: baptiste0928/cargo-install@v1
      with:
        crate: tauri-cli
        version: "1.2.0" 
    - name: use cargo cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: checkout repository
      uses: actions/checkout@v2.5.0
    - name: build
      run: cargo tauri build
