name: build_macos

on:
  workflow_dispatch:

jobs:
  
  clone-x264:
    runs-on: macos-latest
    outputs:
      cache-hit: ${{ steps.cache-libx264.outputs.cache-hit }}
      hash-tag: ${{ steps.get-commit-hash.outputs.hash }}
    steps:
    - name: clone repository
      run: git clone https://github.com/mirror/x264.git -b stable --depth=1
    - name: get commit hash
      working-directory: ./x264
      id: get-commit-hash
      run: |
        echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      shell: bash
    - name: cache libx264
      id: cache-libx264
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/x264
        key: ${{ runner.os }}-libx264-${{ steps.get-commit-hash.outputs.hash }}
    
  build-x264:
    if: needs.clone-x264.outputs.cache-hit != 'true'
    runs-on: macos-latest
    needs: [clone-x264]
    outputs:
      update-build: ${{ needs.clone-x264.outputs.cache-hit != 'true' }}
      hash-tag: ${{ needs.clone-x264.outputs.hash-tag }}
    steps:
    - name: cache libx264
      id: cache-libx264
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/x264
        key: ${{ runner.os }}-libx264-${{ needs.clone-x264.outputs.hash-tag }}
    - name: set up nasm
      uses: ilammy/setup-nasm@v1.4.0
    - name: configure
      working-directory: ./x264
      run: ./configure --prefix=${{github.workspace}}/artifacts/x264 --enable-pic --enable-static --enable-strip --disable-cli --disable-opencl
    - name: make
      working-directory: ./x264
      run: make
    - name: make install
      working-directory: ./x264
      run: make install
    - name: make clean
      working-directory: ./x264
      run: make clean
  
  clone-x265:
    runs-on: macos-latest
    outputs:
      cache-hit: ${{ steps.cache-libx265.outputs.cache-hit }}
      hash-tag: ${{ steps.get-commit-hash.outputs.hash }}
    steps:
    - name: clone repository
      run: git clone https://bitbucket.org/multicoreware/x265_git.git -b stable --depth=1
    - name: get commit hash
      working-directory: ./x265_git
      id: get-commit-hash
      run: |
        echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      shell: bash
    - name: cache libx265
      id: cache-libx265
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/x265
        key: ${{ runner.os }}-libx265-${{ steps.get-commit-hash.outputs.hash }}
        
  build-x265:
    if: needs.clone-x265.outputs.cache-hit != 'true'
    runs-on: macos-latest
    needs: [clone-x265]
    outputs:
      update-build: ${{ needs.clone-x265.outputs.cache-hit != 'true' }}
      hash-tag: ${{ needs.clone-x265.outputs.hash-tag }}
    steps:
    - name: cache libx265
      id: cache-libx265
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/x265
        key: ${{ runner.os }}-libx265-${{ needs.clone-x265.outputs.hash-tag }}
    - name: set up nasm
      uses: ilammy/setup-nasm@v1.4.0
    - name: cmake configure
      working-directory: ./x265_git
      run: cmake ./source -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/artifacts/x265 -DENABLE_SHARED=OFF -DENABLE_CLI=OFF -DENABLE_PIC=ON
    - name: cmake
      working-directory: ./x265_git
      run: cmake --build . --config Release
    - name: cmake install
      working-directory: ./x265_git
      run: cmake --install .
      
  clone-opus:
    runs-on: macos-latest
    outputs:
      cache-hit: ${{ steps.cache-libopus.outputs.cache-hit }}
      hash-tag: ${{ steps.get-commit-hash.outputs.hash }}
    steps:
    - name: clone repository
      run: git clone https://github.com/xiph/opus.git -b 1.1.2 --depth=1
    - name: get commit hash
      working-directory: ./opus
      id: get-commit-hash
      run: |
        echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      shell: bash
    - name: cache libopus
      id: cache-libopus
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/opus
        key: ${{ runner.os }}-libopus-${{ steps.get-commit-hash.outputs.hash }}
        
  build-opus:
    if: needs.clone-opus.outputs.cache-hit != 'true'
    runs-on: macos-latest
    needs: [clone-opus]
    steps:
    - name: cache libopus
      id: cache-libopus
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/opus
        key: ${{ runner.os }}-libx265-${{ needs.clone-opus.outputs.hash-tag }}
    - name: setup autoconf
      run: brew install autoconf
    - name: setup automake
      run: brew install automake
    - name: setup libtool
      run: brew install libtool
    - name: autogen
      working-directory: ./opus
      run: ./autogen.sh
    - name: configure
      working-directory: ./opus
      run: ./configure --host=x86_64 --prefix=${{github.workspace}}/artifacts/opus --enable-static --disable-shared --disable-doc --disable-extra-programs
    - name: make
      working-directory: ./opus
      run: make
    - name: make install
      working-directory: ./opus
      run: make install
    - name: make clean
      working-directory: ./opus
      run: make clean
  
  clone-FFmpeg:
    runs-on: macos-latest
    needs: [clone-x264, clone-x265]
    outputs:
      cache-hit: ${{ steps.cache-FFmpeg.outputs.cache-hit }}
      hash-tag: ${{steps.get-commit-hash.outputs.hash}}-${{needs.clone-x264.outputs.hash-tag}}-${{needs.clone-x265.outputs.hash-tag}}
    steps:
    - name: clone repository
      run: git clone https://github.com/FFmpeg/FFmpeg.git -b release/5.1 --depth=1
    - name: ls
      run: ls -la
    - name: get commit hash
      working-directory: ./FFmpeg
      id: get-commit-hash
      run: |
        echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      shell: bash
    - name: cache FFmpeg
      id: cache-FFmpeg
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/ffmpeg
        key: ${{ runner.os }}-FFmpeg-${{steps.get-commit-hash.outputs.hash}}-${{needs.clone-x264.outputs.hash-tag}}-${{needs.clone-x265.outputs.hash-tag}}
        
  build-FFmpeg:
    if: |
      always() && needs.clone-FFmpeg.outputs.cache-hit != 'true'
    runs-on: macos-latest
    needs: [clone-FFmpeg, build-x264, build-x265]
    steps:
    - name: cache FFmpeg
      id: cache-FFmpeg
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/artifacts/FFmpeg
        key: ${{ runner.os }}-FFmpeg-${{needs.clone-FFmpeg.outputs.hash-tag}}
    - name: set up nasm
      uses: ilammy/setup-nasm@v1.4.0
    - name: show ls
      run: ls -la 
    - name: configure
      working-directory: ./FFmpeg
      run: |
        ./configure \
        --prefix=${{github.workspace}}/artifacts/FFmpeg \
        --extra-cflags=-l${{github.workspace}}/artifacts/x264/include \
        --extra-cflags=-l${{github.workspace}}/artifacts/x265/include \
        --extra-ldflags=-L${{github.workspace}}/artifacts/x264/lib \
        --extra-ldflags=-L${{github.workspace}}/artifacts/x265/lib \
        --disable-all \
        --disable-autodetect \
        --arch=x86_64 \
        --pkg-config-flags=--static \
        --enable-stripping \
        --disable-debug \
        --enable-pic \
        --enable-hardcoded-tables \
        --enable-gpl \
        --enable-version3 \
        --enable-avdevice \
        --enable-avcodec \
        --enable-avformat \
        --disable-doc \
        --disable-htmlpages \
        --disable-manpages \
        --disable-podpages \
        --disable-txtpages \
        --disable-network \
        --enable-libx264 \
        --enable-libx265 \
        --enable-videotoolbox \
        --enable-audiotoolbox \
        --enable-encoder=libx264 \
        --enable-encoder=libx265 \
        --enable-decoder=h264 \
        --enable-decoder=hevc \
        --enable-encoder=h264_videotoolbox \
        --enable-encoder=hevc_videotoolbox \
        --enable-hwaccel=h264_videotoolbox \
        --enable-hwaccel=hevc_videotoolbox \
        --enable-hwaccel=vp9_videotoolbox \
        --enable-parser=h264 \
        --enable-parser=hevc
    - name: make
      working-directory: ./FFmpeg
      run: make
    - name: make install
      working-directory: ./FFmpeg
      run: make install
    - name: make clean
      working-directory: ./FFmpeg
      run: make clean

