name: FFmpeg_macos

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: clone FFMPEG 5.1 release
      run: git clone https://github.com/FFmpeg/FFmpeg.git -b release/5.1 --depth=1
    - name: configure
      run: cd FFmpeg && ./configure --prefix=./artific
    - name: make
      run: make && make install && make clean

